### ISSUE TITLE
Heimdal fails to build on 10.11

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-dupes#554]
```
...snip...
  CC       ext.lo
db.c:57:18: error: too few arguments to function call, expected 2, have 1
    (*d->close)(d);
    ~~~~~~~~~~~  ^
db.c:103:17: error: no member named 'seq' in 'struct __db'
    code = (*d->seq)(d, &key, &value, flag);
             ~  ^
db.c:121:43: error: use of undeclared identifier 'R_NEXT'
        return DB_seq(context, db, flags, entry, R_NEXT);
                                                 ^
db.c:144:46: error: use of undeclared identifier 'R_FIRST'
    return DB_seq(context, db, flags, entry, R_FIRST);
                                             ^
db.c:151:46: error: use of undeclared identifier 'R_NEXT'
    return DB_seq(context, db, flags, entry, R_NEXT);
                                             ^
db.c:182:34: error: too few arguments to function call, expected 5, have 4
    code = (*d->get)(d, &k, &v, 0);
           ~~~~~~~~~             ^
db.c:210:47: error: use of undeclared identifier 'R_NOOVERWRITE'
    code = (*d->put)(d, &k, &v, replace ? 0 : R_NOOVERWRITE);
                                              ^
db.c:232:30: error: too few arguments to function call, expected 4, have 3
    code = (*d->del)(d, &k, 0);
           ~~~~~~~~~         ^
8 errors generated.
```

https://gist.github.com/e8096cdee976e21e4b7f

**Comment by bfontaine** [comment]
This doesn’t seem to be an issue anymore.
